### ISSUE TITLE
[Rss2Email] А без SyndicationFeed

### ISSUE THREAD

**Issue by pavel-b-novikov** [heyheyIvan/nsudotnet#1]
Нене, похвально что вы знаете про SyndicationFeed, но с ним любой дурак может. Я хочу убедиться что про встроенные возможности парсеринга XML вы тоже в курсе, а по сему - направьте всю мощь .NET-а на персеринг XML-я с фидами вручную!

**Comment by heyheyIvan** [comment]
теперь без SyndicationFeed

**Comment by pavel-b-novikov** [comment]
Комар конечно. Я предполагал что вы задействуете атрибуты сериализации
