### ISSUE TITLE
[NumberGuesser] N0

### ISSUE THREAD

**Issue by pavel-b-novikov** [heyheyIvan/nsudotnet#2]
Хорошо и похвально, что вы можете в строки форматов. А какая строка формата должна быть, чтобы всегда выводить числа с десятичной точкой вместо локализованного разделителя и без разделителя разрядов с точностью до 2 знаков (как вы догадались, стандартная задача при написании большинства CRM-ок)?

И еще - странный вопрос, но он вопрос. Если бы я дал вам задачу разработать класс, который занимается парсерингом чисел с плавающей точкой и их валидацией (настраиваемый под разные локали) - вы бы согласились, или это было бы слишком сложное задание? Ответ аргументируйте.

**Comment by heyheyIvan** [comment]
Возможно так:
```csharp
    double someNumber = 123.45678;
    Console.WriteLine("{0}", someNumber.ToString("0.00", System.Globalization.CultureInfo.InvariantCulture));
```

Что-то мне подсказывает, что слишком много тонкостей в парсинге дробных чисел.
В каждой локали свои разделители дробной и целой части (точка, запятая, мумаййиз), а еще есть 
разделители групп разрядов, которые тоже везде разные. Так что, думаю это сложное задание :)

**Comment by pavel-b-novikov** [comment]
Как человек, проделывавший это в Javascript-е подтверждаю. Ответ верный.
