### ISSUE TITLE
[Enigma] Логические операции

### ISSUE THREAD

**Issue by pavel-b-novikov** [heyheyIvan/nsudotnet#3]
Обилие логических операций в первой же строчке натолкнуло меня на старый, но хороший вопрос:

Есть два кода - какой выбросишь, а какой в продакшене используешь?

```с#
if ((User != null) && (User.Age > 10 )) { ... } // A
if ((User.Age > 10 ) && (User != null)) { ... } // B
```

Варианты ответов:
1) A
2) B
3) Без разницы - можно использовать любой вариант

Ответ аргументировать

**Comment by heyheyIvan** [comment]
В варианте B при User == null, вылетит NPE в проверке лево
